require_relative 'models/course'
require_relative 'models/hole'
require_relative 'models/player'
require_relative 'models/round'
require_relative 'models/score'
require_relative 'models/scorecard'
require_relative 'models/tee'
